[package]
build = "build.rs"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "cubes"
publish = false
version = "0.1.0"

[dependencies]
bevy = "0.9"
bevy_wasm = {path = "../../../bevy_wasm"}
cubes_protocol = {path = "../cubes_protocol"}
