[package]
build = "build.rs"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "simple"
publish = false
version = "0.1.0"

[dependencies]
bevy = "0.10"
bevy_wasm = {path = "../../../bevy_wasm"}
simple_protocol = {path = "../simple_protocol"}
