[workspace]
members = [
  "bevy_wasm",
  "bevy_wasm_sys",
  "examples/cubes/cubes",
  "examples/cubes/cubes-protocol",
  "examples/cubes/mod-with-bevy",
  "examples/cubes/mod-without-bevy",
  "examples/simple",
  "examples/simple/scripts",
  "examples/simple/simple-protocol",
]
