[package]
edition = "2021"
name = "cubes_protocol"
publish = false
version = "123.456.789"

[dependencies]
bevy_wasm_shared = {path = "../../../bevy_wasm_shared"}
serde = {version = "1.0", features = ["derive"]}
