[package]
build = "build.rs"
edition = "2021"
name = "simple"
publish = false
version = "0.1.0"

[dependencies]
bevy = "0.9"
bevy_wasm = {path = "../../."}
serde = "1.0"

[dev-dependencies]
scripts = {path = "./scripts"}
