[package]
edition = "2021"
name = "scripts"
version = "0.1.0"

[lib]
# Generate a `.wasm` file instead of a dll
crate-type = ["cdylib"]

[dependencies]
bevy_ecs = "0.9"
bevy_wasm_sys = {path = "../../../bevy_wasm_sys"}
serde = "1.0"
simple-protocol = {path = "../simple-protocol"}
